# Generated by Django 5.2.17 on 2026-09-21 17:39

import apps.content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='заголовок')),
                ('title_uk', models.CharField(max_length=160, null=True, verbose_name='заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='підзаголовок')),
                ('subtitle_uk', models.CharField(blank=True, max_length=255, null=True, verbose_name='підзаголовок')),
                ('eyebrow', models.CharField(blank=True, max_length=60, verbose_name='надпис над заголовком')),
                ('eyebrow_uk', models.CharField(blank=True, max_length=60, null=True, verbose_name='надпис над заголовком')),
                ('image', models.ImageField(blank=True, upload_to='banners/', verbose_name='зображення')),
                ('image_mobile', models.ImageField(blank=True, upload_to='banners/', verbose_name='зображення для мобільного')),
                ('link', models.CharField(blank=True, max_length=300, verbose_name='посилання')),
                ('cta_label', models.CharField(blank=True, max_length=60, verbose_name='текст кнопки')),
                ('cta_label_uk', models.CharField(blank=True, max_length=60, null=True, verbose_name='текст кнопки')),
                ('placement', models.CharField(choices=[('hero', 'Головна — під пошуком'), ('bento', 'Головна — бенто (велика акція)'), ('home_strip', 'Головна — рекламна смуга'), ('catalog_top', 'Каталог — над товарами'), ('product_side', 'Картка товару — збоку')], default='bento', max_length=20, verbose_name='місце показу')),
                ('theme', models.CharField(choices=[('dark', 'Графіт'), ('light', 'Платина'), ('gold', 'Золото')], default='dark', max_length=10, verbose_name='тема')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='показувати з')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='показувати до')),
                ('sort', models.PositiveIntegerField(default=100, verbose_name='порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='активний')),
            ],
            options={
                'verbose_name': 'банер',
                'verbose_name_plural': 'банери та реклама',
                'ordering': ['placement', 'sort', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='заголовок')),
                ('title_uk', models.CharField(max_length=200, null=True, verbose_name='заголовок')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('body', models.TextField(blank=True, verbose_name='текст')),
                ('body_uk', models.TextField(blank=True, null=True, verbose_name='текст')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO title')),
                ('seo_title_uk', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO title')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO description')),
                ('seo_description_uk', models.TextField(blank=True, null=True, verbose_name='SEO description')),
                ('show_in_footer', models.BooleanField(default=True, verbose_name='показувати у футері')),
                ('sort', models.PositiveIntegerField(default=100, verbose_name='порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='опублікована')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'сторінка',
                'verbose_name_plural': 'сторінки',
                'ordering': ['sort', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phones', models.JSONField(default=apps.content.models._default_phones, help_text='Список: {"number","label","viber"}', verbose_name='телефони')),
                ('email', models.EmailField(default='info@premier-parts.com.ua', max_length=254, verbose_name='email')),
                ('address', models.CharField(default='Київ, вул. Вікентія Беретті, 6Б', max_length=255, verbose_name='адреса')),
                ('address_uk', models.CharField(default='Київ, вул. Вікентія Беретті, 6Б', max_length=255, null=True, verbose_name='адреса')),
                ('work_hours', models.CharField(default='Пн–Пт 10:00–18:00', max_length=255, verbose_name='графік роботи')),
                ('work_hours_uk', models.CharField(default='Пн–Пт 10:00–18:00', max_length=255, null=True, verbose_name='графік роботи')),
                ('map_embed_url', models.URLField(blank=True, max_length=1000, verbose_name='посилання для карти (embed)')),
                ('socials', models.JSONField(blank=True, default=dict, help_text='{"telegram": "...", "instagram": "..."}', verbose_name='соцмережі')),
                ('iban_details', models.TextField(blank=True, verbose_name='реквізити для оплати')),
                ('iban_details_uk', models.TextField(blank=True, null=True, verbose_name='реквізити для оплати')),
                ('pickup_note', models.CharField(default='Завдаток 300 грн входить у вартість товару', max_length=255, verbose_name='умови самовивозу')),
                ('pickup_note_uk', models.CharField(default='Завдаток 300 грн входить у вартість товару', max_length=255, null=True, verbose_name='умови самовивозу')),
                ('about_short', models.TextField(blank=True, verbose_name='коротко про компанію')),
                ('about_short_uk', models.TextField(blank=True, null=True, verbose_name='коротко про компанію')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO title')),
                ('seo_title_uk', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO title')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO description')),
                ('seo_description_uk', models.TextField(blank=True, null=True, verbose_name='SEO description')),
            ],
            options={
                'verbose_name': 'налаштування сайту',
                'verbose_name_plural': 'налаштування сайту',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='назва')),
                ('title_uk', models.CharField(max_length=160, null=True, verbose_name='назва')),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='опис')),
                ('description_uk', models.TextField(blank=True, null=True, verbose_name='опис')),
                ('discount_percent', models.PositiveSmallIntegerField(default=0, verbose_name='знижка, %')),
                ('image', models.ImageField(blank=True, upload_to='promotions/', verbose_name='зображення')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='початок')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='кінець')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                ('sort', models.PositiveIntegerField(default=100, verbose_name='порядок')),
                ('categories', models.ManyToManyField(blank=True, to='catalog.category', verbose_name='категорії')),
                ('manufacturers', models.ManyToManyField(blank=True, to='catalog.manufacturer', verbose_name='виробники')),
                ('products', models.ManyToManyField(blank=True, to='catalog.product', verbose_name='товари')),
            ],
            options={
                'verbose_name': 'акція',
                'verbose_name_plural': 'акції',
                'ordering': ['sort', '-discount_percent'],
            },
        ),
    ]
