# Generated by Django 5.2.17 on 2026-09-21 18:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='номер')),
                ('access_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('kind', models.CharField(choices=[('regular', 'Звичайне'), ('quick', 'В 1 клік')], default='regular', max_length=10, verbose_name='тип')),
                ('status', models.CharField(choices=[('new', 'Нове'), ('confirmed', 'Підтверджене'), ('shipped', 'Відправлене'), ('completed', 'Виконане'), ('canceled', 'Скасоване')], default='new', max_length=12, verbose_name='статус')),
                ('customer_name', models.CharField(blank=True, max_length=160, verbose_name="ім'я")),
                ('phone', models.CharField(max_length=20, verbose_name='телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('delivery_method', models.CharField(choices=[('np_branch', 'Нова Пошта — відділення'), ('np_courier', "Нова Пошта — кур'єр"), ('pickup', 'Самовивіз (Київ)'), ('taxi', 'Таксі по Києву')], default='np_branch', max_length=12, verbose_name='доставка')),
                ('city', models.CharField(blank=True, max_length=160, verbose_name='місто')),
                ('np_branch', models.CharField(blank=True, max_length=255, verbose_name='відділення НП')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='адреса')),
                ('payment_method', models.CharField(choices=[('iban', 'Оплата на рахунок ФОП'), ('card_pickup', 'Карткою при самовивозі'), ('cash_pickup', 'Готівкою при самовивозі')], default='iban', max_length=12, verbose_name='оплата')),
                ('comment', models.TextField(blank=True, verbose_name='коментар клієнта')),
                ('car_snapshot', models.JSONField(blank=True, default=dict, verbose_name='авто клієнта')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='сума без знижки')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='знижка')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='до сплати')),
                ('manager_note', models.TextField(blank=True, verbose_name='нотатка менеджера')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='створено')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'замовлення',
                'verbose_name_plural': 'замовлення',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='назва')),
                ('sku', models.CharField(blank=True, max_length=80, verbose_name='артикул')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ціна')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ціна без знижки')),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='кількість')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='сума')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product')),
            ],
            options={
                'verbose_name': 'позиція',
                'verbose_name_plural': 'позиції',
            },
        ),
    ]
