# Generated by Django 5.2.17 on 2026-09-21 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='назва')),
                ('family', models.CharField(blank=True, help_text='Напр. «Passat» для «Passat B7 USA»', max_length=80, verbose_name='сімейство')),
                ('market', models.CharField(choices=[('eu', 'Європа'), ('usa', 'США'), ('asia', 'Азія'), ('other', 'Не вказано')], default='other', max_length=8, verbose_name='ринок')),
                ('slug', models.SlugField(max_length=140)),
                ('legacy_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'модель',
                'verbose_name_plural': 'моделі',
                'ordering': ['make__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='назва')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('logo', models.ImageField(blank=True, upload_to='makes/', verbose_name='логотип')),
                ('is_popular', models.BooleanField(default=False, verbose_name='популярна')),
                ('sort', models.PositiveIntegerField(default=100, verbose_name='порядок')),
                ('legacy_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'марка авто',
                'verbose_name_plural': 'марки авто',
                'ordering': ['sort', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='назва')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('logo', models.ImageField(blank=True, upload_to='manufacturers/', verbose_name='логотип')),
                ('country', models.CharField(blank=True, max_length=60, verbose_name='країна')),
            ],
            options={
                'verbose_name': 'виробник деталей',
                'verbose_name_plural': 'виробники деталей',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='назва')),
                ('name_uk', models.CharField(max_length=160, null=True, verbose_name='назва')),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Ключ іконки: light, body, radiator, mirror, glass, exhaust, door, bumper…', max_length=32, verbose_name='іконка')),
                ('image', models.ImageField(blank=True, upload_to='categories/', verbose_name='зображення')),
                ('description', models.TextField(blank=True, verbose_name='опис')),
                ('description_uk', models.TextField(blank=True, null=True, verbose_name='опис')),
                ('sort', models.PositiveIntegerField(default=100, verbose_name='порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category', verbose_name='батьківська')),
            ],
            options={
                'verbose_name': 'категорія',
                'verbose_name_plural': 'категорії',
                'ordering': ['sort', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_from', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='рік від')),
                ('year_to', models.PositiveSmallIntegerField(blank=True, help_text='Порожньо — випускається досі', null=True, verbose_name='рік до')),
                ('slug', models.SlugField(max_length=40)),
                ('legacy_id', models.CharField(blank=True, db_index=True, max_length=40)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='catalog.carmodel', verbose_name='модель')),
            ],
            options={
                'verbose_name': 'серія (роки)',
                'verbose_name_plural': 'серії (роки)',
                'ordering': ['model__make__name', 'model__name', 'year_from'],
                'unique_together': {('model', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='carmodel',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='catalog.make', verbose_name='марка'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='назва')),
                ('name_uk', models.CharField(max_length=300, null=True, verbose_name='назва')),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='артикул')),
                ('description', models.TextField(blank=True, verbose_name='опис')),
                ('description_uk', models.TextField(blank=True, null=True, verbose_name='опис')),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='0 — «Ціну уточнюйте»', max_digits=10, verbose_name='ціна, ₴')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='стара ціна, ₴')),
                ('stock_status', models.CharField(choices=[('in_stock', 'В наявності'), ('on_order', 'Під замовлення'), ('out_of_stock', 'Немає в наявності')], default='in_stock', max_length=16, verbose_name='наявність')),
                ('side', models.CharField(choices=[('left', 'Ліва'), ('right', 'Права'), ('both', 'Комплект'), ('none', '—')], default='none', max_length=8, verbose_name='сторона')),
                ('position', models.CharField(choices=[('front', 'Передня'), ('rear', 'Задня'), ('none', '—')], default='none', max_length=8, verbose_name='розташування')),
                ('condition', models.CharField(default='new', max_length=20, verbose_name='стан')),
                ('is_active', models.BooleanField(default=True, verbose_name='активний')),
                ('is_featured', models.BooleanField(default=False, verbose_name='хіт продажу')),
                ('popularity', models.PositiveIntegerField(default=0, verbose_name='популярність')),
                ('legacy_url', models.URLField(blank=True, max_length=500, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='категорія')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.manufacturer', verbose_name='виробник')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товари',
                'ordering': ['-popularity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PartNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=80, verbose_name='номер')),
                ('normalized', models.CharField(db_index=True, editable=False, max_length=80)),
                ('kind', models.CharField(choices=[('sku', 'Артикул'), ('oem', 'OEM'), ('cross', 'Крос-номер')], default='oem', max_length=8, verbose_name='тип')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_numbers', to='catalog.product')),
            ],
            options={
                'verbose_name': 'номер деталі',
                'verbose_name_plural': 'номери деталі (артикул, OEM, кроси)',
            },
        ),
        migrations.CreateModel(
            name='Fitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitments', to='catalog.generation', verbose_name='авто')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitments', to='catalog.product')),
            ],
            options={
                'verbose_name': 'сумісність',
                'verbose_name_plural': 'сумісність з авто',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/%Y/', verbose_name='фото')),
                ('alt', models.CharField(blank=True, max_length=300)),
                ('sort', models.PositiveIntegerField(default=0)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
            options={
                'verbose_name': 'фото',
                'verbose_name_plural': 'фото',
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='carmodel',
            unique_together={('make', 'slug')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'category'], name='catalog_pro_is_acti_1a8de5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured'], name='catalog_pro_is_feat_94b8d5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='partnumber',
            unique_together={('product', 'normalized')},
        ),
        migrations.AlterUniqueTogether(
            name='fitment',
            unique_together={('product', 'generation')},
        ),
    ]
