# Generated by Django 5.2.17 on 2026-09-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_supplier_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='generation',
            name='source_label',
            field=models.CharField(blank=True, max_length=120, verbose_name='назва типу з джерела'),
        ),
    ]
