# Generated by Django 5.2.17 on 2026-09-27 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_generation_source_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaAttributeName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized_name', models.CharField(max_length=160, unique=True)),
                ('name', models.CharField(max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name='FormaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveBigIntegerField(unique=True)),
                ('title', models.CharField(max_length=160)),
                ('item_group', models.CharField(blank=True, max_length=160)),
                ('item_sub_group', models.CharField(blank=True, max_length=160)),
                ('is_leaf', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='forma_link', to='catalog.category')),
            ],
        ),
        migrations.CreateModel(
            name='FormaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.CharField(max_length=80)),
                ('normalized_item_no', models.CharField(max_length=80, unique=True)),
                ('supplier_customer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('retail_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity_raw', models.CharField(blank=True, max_length=40)),
                ('in_stock', models.BooleanField(default=False)),
                ('discontinued', models.BooleanField(default=False)),
                ('short_text', models.TextField(blank=True)),
                ('search_description', models.TextField(blank=True)),
                ('criteria_line', models.TextField(blank=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='forma.formacategory')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='forma_item', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='FormaSyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('full', 'Повна'), ('fast', 'Швидка')], max_length=8)),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('running', 'Виконується'), ('completed', 'Завершено'), ('completed_with_errors', 'Завершено з помилками'), ('failed', 'Помилка')], db_index=True, default='pending', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('categories_processed', models.PositiveIntegerField(default=0)),
                ('products_processed', models.PositiveIntegerField(default=0)),
                ('products_created', models.PositiveIntegerField(default=0)),
                ('products_updated', models.PositiveIntegerField(default=0)),
                ('vehicles_processed', models.PositiveIntegerField(default=0)),
                ('fitments_created', models.PositiveIntegerField(default=0)),
                ('errors_count', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(default=list)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormaVehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=240, unique=True)),
                ('external_type_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('type_name', models.CharField(blank=True, max_length=120)),
                ('type_range', models.CharField(blank=True, max_length=120)),
                ('raw_data', models.JSONField(default=dict)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('generation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='forma_type', to='catalog.generation')),
            ],
        ),
        migrations.CreateModel(
            name='FormaItemAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forma.formaattributename')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='forma.formaitem')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('item', 'attribute'), name='forma_item_attribute_unique')],
            },
        ),
        migrations.CreateModel(
            name='FormaVehicleFitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.JSONField(default=dict)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_fitments', to='forma.formaitem')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_fitments', to='forma.formavehicletype')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('item', 'vehicle'), name='forma_item_vehicle_unique')],
            },
        ),
        migrations.CreateModel(
            name='FormaWarehouseStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_code', models.CharField(max_length=120)),
                ('location_name', models.CharField(blank=True, max_length=120)),
                ('quantity_raw', models.CharField(blank=True, max_length=40)),
                ('quantity_min', models.PositiveIntegerField(blank=True, null=True)),
                ('quantity_is_more_than', models.BooleanField(default=False)),
                ('reserved_raw', models.CharField(blank=True, max_length=40)),
                ('raw_data', models.JSONField(default=dict)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='forma.formaitem')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('item', 'location_code'), name='forma_item_warehouse_unique')],
            },
        ),
    ]
