# Generated by Django 5.2.17 on 2026-09-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formasyncjob',
            name='heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formavehicletype',
            name='specs',
            field=models.JSONField(default=dict),
        ),
    ]
