# Generated by Django 5.2.17 on 2026-09-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forma', '0002_formasyncjob_heartbeat_at_formavehicletype_specs'),
    ]

    operations = [
        migrations.AddField(
            model_name='formacategory',
            name='source_image_path',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
