# Generated by Django 5.2.17 on 2026-09-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchSynonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=80, unique=True, verbose_name='слово')),
                ('synonyms', models.CharField(help_text='Через кому: passat, пассат', max_length=500, verbose_name='синоніми')),
                ('is_active', models.BooleanField(default=True, verbose_name='активний')),
            ],
            options={
                'verbose_name': 'синонім пошуку',
                'verbose_name_plural': 'синоніми пошуку',
                'ordering': ['term'],
            },
        ),
    ]
