# Generated by Django 5.2.17 on 2026-09-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VinDecodeCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'кеш розшифровки VIN',
                'verbose_name_plural': 'кеш розшифровки VIN',
            },
        ),
        migrations.CreateModel(
            name='VinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17, verbose_name='VIN')),
                ('name', models.CharField(blank=True, max_length=120, verbose_name="ім'я")),
                ('phone', models.CharField(max_length=20, verbose_name='телефон')),
                ('part_query', models.CharField(blank=True, max_length=500, verbose_name='яка деталь потрібна')),
                ('comment', models.TextField(blank=True, verbose_name='коментар')),
                ('decoded', models.JSONField(blank=True, default=dict, verbose_name='розшифровка')),
                ('status', models.CharField(choices=[('new', 'Новий'), ('in_progress', 'В роботі'), ('done', 'Опрацьовано')], default='new', max_length=16, verbose_name='статус')),
                ('manager_note', models.TextField(blank=True, verbose_name='нотатка менеджера')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='створено')),
            ],
            options={
                'verbose_name': 'запит за VIN',
                'verbose_name_plural': 'запити за VIN',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wmi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='код')),
                ('make_name', models.CharField(max_length=80, verbose_name='марка')),
                ('country', models.CharField(blank=True, max_length=80, verbose_name='країна')),
            ],
            options={
                'verbose_name': 'код виробника (WMI)',
                'verbose_name_plural': 'коди виробників (WMI)',
                'ordering': ['code'],
            },
        ),
    ]
